### ISSUE TITLE
Send bug report

### ISSUE THREAD

**Issue by CavalcanteLeo** [rahuljiresal/BugReportKit#11]
How to send a bug?

I took a quick look on your code, and found only this:

```
- (void)sendBugReportWithImage:(UIImage*)image text:(NSString*)text completionHandler:(void(^)(NSError* error, NSString* url))handler
```

Is it right? how do I implement?

**Comment by rahuljiresal** [comment]
You need to first create an object of a reporter (I have written it for Github, Gitlab, JIRA and Email. You can also write a custom one). Then instantiate `BugReportKit` with that reporter. 

After that it done, taking a screenshot will invoke the reporting.

Take a look at the ReadMe. Hope this helps.

P.S. Also keep in mind that some reporters (Github, JIRA) need an `ImageUploader` to upload the images used in the bug reports. I have written an Amazon S3 Image Uploader, but you can write your own too.
